#!/bin/bash
#
# Indentation style used for PHG source code
#
indent -gnu -psl -i4 -npcs -cli4 -br -nce -brs -nbs -ncs -nsob -npro \
	-T FLOAT -T INT -T UINT -T SHORT -T USHORT -T CHAR -T BYTE \
	-T GRID -T SIMPLEX -T BOOLEAN -T GTYPE -T BTYPE -T COORD \
	-T GRID_ELEM_TYPE -T ELEM_TYPE -T ELEMENT -T SFC -T SFC2 -T DOTS \
	-T USER_DATA_FUNC -T PARTITIONER -T SFC_FLOAT -T EIGEN_SOLVER \
	-T ADD_TETRA_FUNC -T EDGE_INFO -T FACE_INFO -T FUNC2TET -T ELEM_INFO \
	-T RNEIGHBOUR -T EXPR -T VTYPE -T OPTION -T OPTION_HANDLER -T PFunc_t \
	-T QUAD -T PERIOD -T PetscInt -T PetscMPIInt -T PetscErrorCode \
	-T PetscTruth -T MPI_Comm -T BDRY_MAP_FUNC \
	-T DOF_USER_FUNC -T DOF_INIT_FUNC -T DOF_INTERP_FUNC \
	-T DOF_BASIS_FUNC -T DOF_BASIS_GRAD -T DOF_TYPE -T DOF \
	-T DOF_MAP_FUNC -T HP_INFO -T HP_TYPE -T VEF_MAP -T VEF_MAP2 \
	-T DOF_TYPES_INFO -T NEIGHBOUR_DATA -T DOF_OP \
	-T MATRIX_ROW -T SOLVER -T OEM_SOLVER -T PC_PROC -T SOLVER_PC \
	-T VERTEX_t -T LIST -T RLIST -T INDEX_t -T TABLE \
	-T RNEIGHBOUR_t -T VERT_t -T FACE_t -T SIMPLEX_t \
	-T INDEX -T DIAG_ROW -T B_LIST -T QUAD_CACHE -T QUAD_CACHE_LIST \
	-T SIMPLE_TET -T SUBREGION_FUNC -T OCT_TREE -T CUBE \
	-T COMM_INFO -T MAP -T NEIGHBOUR_MAP -T NEIGHBOUR_INFO \
	-T MAPPING_USER_FUNC -T MAPPING_USER_FUNC_LAMBDA \
	-T MAPPING_INIT_FUNC -T MAPPING_BASIS_FUNC -T MAPPING_BASIS_GRAD \
	-T MAPPING_MAP_FUNC -T MAPPING_TYPE -T MAPPING \
	-T STRATEGY -T MASS_LUMPING -T MAT_OP -T MAT -T VEC -T MV_FUNC \
	-T MAT_ROW -T BDRY_EQNS -T MAT_TYPE -T MAT_MODE -T L2DATA \
	"$@"
